# Generated by Django 5.2.7 on 2025-10-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='bundle_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='network',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='size_label',
            field=models.CharField(max_length=50),
        ),
    ]
