# Generated by Django 5.2.7 on 2025-11-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
