# Generated by Django 5.2.7 on 2025-10-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bundle_is_active_alter_bundle_bundle_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundle',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bundle',
            name='network',
        ),
        migrations.RemoveField(
            model_name='bundle',
            name='size_label',
        ),
        migrations.AddField(
            model_name='bundle',
            name='datadash_code',
            field=models.CharField(blank=True, help_text='Exact Datadash plan id/code for vending', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='bundle',
            name='name',
            field=models.CharField(default='Default Bundle', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bundle',
            name='bundle_code',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
