# Generated by Django 5.2.7 on 2025-10-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_bundle_created_at_remove_bundle_network_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundle',
            name='bundle_code',
        ),
        migrations.RemoveField(
            model_name='bundle',
            name='datadash_code',
        ),
        migrations.RemoveField(
            model_name='bundle',
            name='is_active',
        ),
        migrations.AddField(
            model_name='bundle',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bundle',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
