# Generated by Django 5.2.7 on 2025-10-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_bundle_bundle_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='code',
            field=models.CharField(default="'default'", max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
