# Generated by Django 5.2.7 on 2025-10-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_bundle_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='api_transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
