# Generated by Django 5.2.7 on 2025-10-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_purchase_paid_at_alter_purchase_api_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='color',
            field=models.CharField(default='#3498db', max_length=20),
        ),
        migrations.AddField(
            model_name='bundle',
            name='logo',
            field=models.CharField(blank=True, help_text="Static path to network logo (e.g. 'images/mtn.png')", max_length=200),
        ),
        migrations.AddField(
            model_name='bundle',
            name='network',
            field=models.CharField(default='MTN', max_length=50),
        ),
    ]
