# Generated by Django 5.2.7 on 2025-11-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_apikey_apiaccesslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='logo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
